### ISSUE TITLE
--ignore does not work (?)

### ISSUE THREAD

**Issue by francoismassart** [danielkalen/foreach-cli#4]
Using npm 4.7.0, I have a script in package.json:

`"css-minify": "foreach -g \"public/static/css/**/*.css\" -i \"public/static/css/**/*.min.css\" -x \"cleancss --level 1 #{path} -o #{dir}/#{name}.min.css\" --no-c"`

Running this script, I was expecting cleancss to only run with css files not ending by ".min.css"...

But it does not ignore the .min.css files.

It'll keep adding min.css files!

` ✔ Executing command: public/static/css/index.min.css`

then
```
 ✔ Executing command: public/static/css/index.min.css
 ✔ Executing command: public/static/css/index.min.min.css
```

...

Is this normal ? I thought the .min.css files were ignored via the `-i` argument...

**Comment by francoismassart** [comment]
I found a solution by using a `pre` script that removes all the `.min.css` files:

`"precss-minify": "foreach -g \"public/static/css/**/*.min.css\" -x \"rm #{path}\""`

But still, it should work with --ignore, shouldn't it ?

**Comment by francoismassart** [comment]
OK, I think I know why it doesn't work...

If I look at my copy of the installed files from `npm install foreach-cli`, I don't see any trace of the `ignore` option in the source code. 

The source files from npmjs are outdated.

The sources on github are up to date but not on npmjs so I believe you forgot to run `npm publish`...
You may need to run `npm version patch` in order to change the version from `1.7.3` to `1.7.4`.

@danielkalen Please keep me informed.

**Comment by danielkalen** [comment]
sorry I'm replying just now I've been busy lately. I'll be able to take a look at your PR and checkout the issue tomorrow afternoon EST so I'll keep you posted. Thanks
